apiVersion: v1
kind: Pod
metadata:
  name: kuweb-pod
  labels:
    app: kuweb-label
spec:
  containers:
  - name: kuweb
    image: testweb:1.0
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
  - name: ubuntu-linux
    image: ismoon/ubuntu-linux:2.0
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    command: ["tail"]
    args: ["-f", "/dev/null"]